### ISSUE TITLE
Hyperparameters for reproducing results

### ISSUE THREAD

**Issue by yashbhalgat** [akanimax/relu_fields#10]
@akanimax hi again! I have been playing around with the code for not too long, but I am trying to reproduce the results (from the paper) for the Lego dataset. Specifically, I am trying to reproduce the PSNR and the speed of training.

I ran `python train_sh_based_voxel_grid_with_posed_images.py -d ./data/nerf_synthetic/lego/ -o ./logs/`. The training was quite slower than expected -- it took about 3000 iterations (which was about 90 minutes on my `GeForce GTX TITAN X`) to reach a PSNR of approx. `21`.

The final test PSNR (after 8k iters) was about `27.4` compared to `28.83` from the paper. 

I am definitely missing something. Can you please share the command that may reproduce the speed+PSNR results from the paper? Would really appreciate it! :) 

Thank you,
@yashbhalgat

**Comment by akanimax** [comment]
:confused:, interesting ... 
Could you post the tensorboard logs screenshots here? Need to look at the PSNR v/s iterations chart.

**Comment by yashbhalgat** [comment]
Sure! This is what I see for Test PSNR:
![image](https://user-images.githubusercontent.com/8559512/175834286-97d6adc0-2c1a-4a05-90ca-985d2e9ca940.png)

**Comment by akanimax** [comment]
Right, it remains almost flat after the first 500 iterations in each stage. Could you try the latest commit on the `bells_and_whistles` branch? I changed those hyperparams recently.

**Comment by yashbhalgat** [comment]
Ok, I will try it out right away. Thanks for your prompt responses on a late Sunday night! :smile:

**Comment by akanimax** [comment]
Ah, no worries Yash! Everyday - everytime is the same for us now :sweat_smile:!
Cheers!

**Comment by yashbhalgat** [comment]
@akanimax, I tried the latest commit on the `bells_and_whistles` branch. The training is faster as expected, but the final performance is worse than before. The final PSNR is `26.61` after full training now :confused: 
![image](https://user-images.githubusercontent.com/8559512/175836162-590c3b4d-3777-47a3-b7ff-6ad699727c1b.png)

**Comment by akanimax** [comment]
Okay, cool this is indeed helpful. This narrows down my search for hyperparameters in the sweep we did 😄. From this point onwards, I remember doing: increasing the `ray_batch_size` and tuning the `learning-rate` a bit.. 
Working on something else atm. Will get back to you soon. 

Quick check though: You are running these on the 400x400 versions right? Need to set downsample_factor=2 for NeRF-comparisons.

**Comment by akanimax** [comment]
Also, check the console-log for actual training time. Tensorboard also records the time spent testing and rendering heavy visualizations for feedback. 

Thanks a lot for helping in this regard. I appreciate it.

**Comment by yashbhalgat** [comment]
> Okay, cool this is indeed helpful. This narrows down my search for hyperparameters in the sweep we did smile. From this point onwards, I remember doing: increasing the `ray_batch_size` and tuning the `learning-rate` a bit.. Working on something else atm. Will get back to you soon.
> 
> Quick check though: You are running these on the 400x400 versions right? Need to set downsample_factor=2 for NeRF-comparisons.

Ok, looking forward to the final hyperparameters! :smile: 
Just checked that it is indeed 400x400 images. 

And no problem! I am also learning a lot in the process. :)

**Comment by akanimax** [comment]
Awesome! 
so I got some time to think around this, if it’s not too much trouble could  you also run the same experiment on the Grid versions? Just set ‘use_relu_field=False’.
This will ensure that this is indeed a hyparameters issue and not an underlying subtle bug. 

Because, the latter would be a nightmare 😅. I spent a lot of time working on this clean and refactored code. Hopefully this is as bug-free as possible.

also, the rendered animations (new script in bells_and_whistles) are at times more informative than the PSNR scores 🙂.

**Comment by yashbhalgat** [comment]
Ok, I ran the same experiment (i.e. with hyperparams from the latest commit on `bells_and_whistles`) with `use_relu_field=False` and the final PSNR is `23.12` (much worse, which is good? :smile: )
![image](https://user-images.githubusercontent.com/8559512/175941178-b3b49374-b05a-4b85-860d-f9cad49997a6.png)

So, I guess it's the hyperparameters.

**Comment by akanimax** [comment]
Phew 😅! Deep Breaths. 
The refactoring efforts didn't go in vain. Hyperparameters it is indeed!

Well, this is a not-so-solicited aspect of ML-research, but as long as the overall behaviours are similar, the research keeps moving forward 😄. 

+100 XP
You have unlocked a tid-bit of behind-the-scene 😄 socio-political aspects 😆 or ReLU-Fields. If it's okay, lets take the rest of the discussion offline. Some things are better done in the shadows 🌚 🙂!

Closing this issue for now, but please feel free to re-open if something comes-up. 

Pleasure doing business (RESEARCH) with you 🖖!

**Comment by Ketoo117** [comment]
hello, My test results always be less than the value that you reported in the paper about two units of PSNR .  How can I resolve it？

**Comment by akanimax** [comment]
Hey @Ketoo117,

Here is a test on the latest master:
Scene: `Lego Bulldozer`
PSNR: `28.17`
Training time: `00:13:45:00`
benchmark GPU: `A100-32GB`
grid_size:  `128^3`

Params:
```python train_sh_based_voxel_grid_with_posed_images.py -d ../../data/3d-atom/nerf_synthetic/lego -o ../../logs/lego_optimized 

** Important ones **
--ray_batch_size 32768 
--train_num_samples_per_ray 1024
--num_iterations_per_stage 1000 
--lr_decay_steps_per_stage 800 
** Rest are minor training related parameters same as default**

--save_frequency 500 
--test_frequency 500 
--feedback_frequency 100 
--summary_frequency 50
```

I hadn't used these params in the code as default, since I am targetting the code for regular users with GTX and RTX GPUs 🙂 (8GB of GPU mem).

But I think I should add this section to the Readme, for researchers using this as baseline.

https://user-images.githubusercontent.com/16590868/220740351-f832b184-de9e-4af3-9164-35d02b55ebc5.mp4
