### ISSUE TITLE
Is the code working now?

### ISSUE THREAD

**Issue by Derry-Xing** [akanimax/relu_fields#11]
Dear authors,

May I ask if the code working now to give a preliminary overview?

Thanks!

**Comment by Derry-Xing** [comment]
OK， I see some progress on Issue #10 
Close it and look forward to the final.

**Comment by Derry-Xing** [comment]
CAn you provide the script that converts transorms_train.json to your customer format?

**Comment by akanimax** [comment]
@Derry-Xing, 
Yes the code is working, and has no bugs reported 😄 👍 . So you can go ahead and start playing around with it. I have unfortunately not had the time to work on PR #9 yet, but I can try to work a bit on it tomorrow 😓. 

In the meantime, please feel free to try the code with this 3d-atom data formatted Lego Bulldozer scene at -> https://drive.google.com/drive/folders/1jkIsuWeAIz-NtPFOiG4d01tGT-zok1WM.
