### ISSUE TITLE
Dataset format specifications

### ISSUE THREAD

**Issue by yashbhalgat** [akanimax/relu_fields#8]
Hi @akanimax , thanks for open-sourcing the code! Really appreciate it.

It seems like the training script expects a particular dataset folder-format that is different from nerf-synthetic format (see lego [here](https://drive.google.com/drive/folders/1lrDkQanWtTznf48FCaW5lX9ToRdNDF1a)). I was wondering if you have some script that can convert the Nerf synthetic dataset into the format required by the training script? Thanks! :)

**Comment by yashbhalgat** [comment]
Opened a pull request #9 for this one, if it's helpful. :)

**Comment by akanimax** [comment]
Hi Yash (@yashbhalgat ) :smile:! You got me :skull:. I was hoping I could get at least 2 weeks before someone figured out that the data is in a different format :sweat_smile:, giving me some breathing space to catch-up on Stranger Things S04 :laughing:. 

Anyway, I basically wanted to create a simple format which had just enough enough information for these bare-bone experiments, and which was easily readable to humans as well :smile:. 

you can find a sample `thre3d_atom`-data-format nerf_hotdog scene for reference:
here - > https://drive.google.com/drive/folders/1E_pa4VyjOqMAKjG4a62tQ7L9cbqUKAkw?usp=sharing
Check in `data/sample`

**Comment by akanimax** [comment]
Ahha, saw the PR just now! Thanks for creating it :+1:.

**Comment by akanimax** [comment]
PR #9  has been merged. Cheers!
